INSERT INTO public.category (category_name) VALUES
('디지털/인터넷'),
('일상 생활'),
('직장/학교'),
('연애/관계'),
('유행/패션'),
('감정/상태'),
('소비/경제'),
('음식/취미'),
('기타');

INSERT INTO public.slang ( id, created_time, modified_time, slang_meaning, slang_name, slang_substitutes, slang_example, category_id )  VALUES (gen_random_uuid(),NOW(),NOW(), '인기 있는 사람','인싸','','우리 반에서 제일 인싸는 민수야.',(SELECT id FROM public.category WHERE category_name = '디지털/인터넷'));
INSERT INTO public.slang ( id, created_time, modified_time, slang_meaning, slang_name, slang_substitutes, slang_example, category_id )  VALUES (gen_random_uuid(),NOW(),NOW(), '매우 재미있음을 뜻하는 말','꿀잼','매우 재미있는','이번 주말에는 넷플릭스에서 꿀잼 드라마를 봤어.',(SELECT id FROM public.category WHERE category_name = '디지털/인터넷'));
INSERT INTO public.slang ( id, created_time, modified_time, slang_meaning, slang_name, slang_substitutes, slang_example, category_id )  VALUES (gen_random_uuid(),NOW(),NOW(), '집단 내에서 소외되어 있거나 적극적으로 어울리지 않는 사람을 이르는 말','아싸','외톨이','나는 대학교에서 아싸야.',(SELECT id FROM public.category WHERE category_name = '디지털/인터넷'));
INSERT INTO public.slang ( id, created_time, modified_time, slang_meaning, slang_name, slang_substitutes, slang_example, category_id )  VALUES (gen_random_uuid(),NOW(),NOW(), '재미가 없음을 뜻하는 말','노잼','재미없는','그 영화는 너무 노잼이라서 보다가 잤어.',(SELECT id FROM public.category WHERE category_name = '디지털/인터넷'));
INSERT INTO public.slang ( id, created_time, modified_time, slang_meaning, slang_name, slang_substitutes, slang_example, category_id )  VALUES (gen_random_uuid(),NOW(),NOW(), '매우 힘든 상황에서도 포기하지 않고 버티는 것을 뜻하는 말','존버','인내심 있게 버티기','주식 투자에서 존버하면 수익을 얻을 수 있어.',(SELECT id FROM public.category WHERE category_name = '디지털/인터넷'));
INSERT INTO public.slang ( id, created_time, modified_time, slang_meaning, slang_name, slang_substitutes, slang_example, category_id )  VALUES (gen_random_uuid(),NOW(),NOW(), '취향을 존중한다는 뜻','취존','취향 존중','너의 취미를 취존할게.',(SELECT id FROM public.category WHERE category_name = '디지털/인터넷'));
INSERT INTO public.slang ( id, created_time, modified_time, slang_meaning, slang_name, slang_substitutes, slang_example, category_id )  VALUES (gen_random_uuid(),NOW(),NOW(), '매우 인정한다는 뜻','킹정','매우 인정함','이번 프로젝트는 정말 킹정이야.',(SELECT id FROM public.category WHERE category_name = '디지털/인터넷'));
INSERT INTO public.slang ( id, created_time, modified_time, slang_meaning, slang_name, slang_substitutes, slang_example, category_id )  VALUES (gen_random_uuid(),NOW(),NOW(), '호구처럼 이용당하는 사람을 뜻하는 말','흑우','호구','그 가게는 흑우들만 가는 곳이야.',(SELECT id FROM public.category WHERE category_name = '디지털/인터넷'));
INSERT INTO public.slang ( id, created_time, modified_time, slang_meaning, slang_name, slang_substitutes, slang_example, category_id )  VALUES (gen_random_uuid(),NOW(),NOW(), '엄격, 근엄, 진지하다는 뜻','엄근진','엄격하고 진지한','선생님은 수업 시간에 항상 엄근진하셔.',(SELECT id FROM public.category WHERE category_name = '디지털/인터넷'));
INSERT INTO public.slang ( id, created_time, modified_time, slang_meaning, slang_name, slang_substitutes, slang_example, category_id )  VALUES (gen_random_uuid(),NOW(),NOW(), '꾸민 듯 안 꾸민 듯 자연스러운 스타일을 뜻하는 말','꾸안꾸','자연스러운 스타일','오늘은 꾸안꾸로 입고 왔어.',(SELECT id FROM public.category WHERE category_name = '일상 생활'));
INSERT INTO public.slang ( id, created_time, modified_time, slang_meaning, slang_name, slang_substitutes, slang_example, category_id )  VALUES (gen_random_uuid(),NOW(),NOW(), '만나서 반가워 잘 부탁해라는 뜻','만반잘부','만나서 반가워 잘 부탁해','오늘 처음 만난 친구에게 만반잘부라고 인사했어.',(SELECT id FROM public.category WHERE category_name = '일상 생활'));
INSERT INTO public.slang ( id, created_time, modified_time, slang_meaning, slang_name, slang_substitutes, slang_example, category_id )  VALUES (gen_random_uuid(),NOW(),NOW(), '스스로 불러온 재앙이라는 뜻','스불재','스스로 자초한 불행','내가 스불재를 당해서 지금 너무 힘들어.',(SELECT id FROM public.category WHERE category_name = '일상 생활'));
INSERT INTO public.slang ( id, created_time, modified_time, slang_meaning, slang_name, slang_substitutes, slang_example, category_id )  VALUES (gen_random_uuid(),NOW(),NOW(), '알아서 잘 딱 깔끔하고 센스있게라는 뜻','알잘딱깔센','알아서 잘 처리함','이번 프레젠테이션 준비는 알잘딱깔센하게 했어.',(SELECT id FROM public.category WHERE category_name = '일상 생활'));
INSERT INTO public.slang ( id, created_time, modified_time, slang_meaning, slang_name, slang_substitutes, slang_example, category_id )  VALUES (gen_random_uuid(),NOW(),NOW(), '사귀기 전 단계를 뜻하는 말','삼귀자','사귀기 전 단계','우리 이제 삼귀자.',(SELECT id FROM public.category WHERE category_name = '일상 생활'));
INSERT INTO public.slang ( id, created_time, modified_time, slang_meaning, slang_name, slang_substitutes, slang_example, category_id )  VALUES (gen_random_uuid(),NOW(),NOW(), '자연스러운 만남 추구라는 뜻','자만추','자연스러운 만남 추구','나는 자만추가 좋아.',(SELECT id FROM public.category WHERE category_name = '일상 생활'));
INSERT INTO public.slang ( id, created_time, modified_time, slang_meaning, slang_name, slang_substitutes, slang_example, category_id )  VALUES (gen_random_uuid(),NOW(),NOW(), '복잡한 세상 편하게 살자라는 뜻','복세편살','편하게 살기','복세편살하며 살고 싶어.',(SELECT id FROM public.category WHERE category_name = '일상 생활'));
INSERT INTO public.slang ( id, created_time, modified_time, slang_meaning, slang_name, slang_substitutes, slang_example, category_id )  VALUES (gen_random_uuid(),NOW(),NOW(), '좋아요 댓글 구독 알림설정의 줄임말','좋댓구알','좋아요, 댓글, 구독, 알림설정','유튜브 영상을 볼 때는 꼭 좋댓구알 해주세요.',(SELECT id FROM public.category WHERE category_name = '일상 생활'));
INSERT INTO public.slang ( id, created_time, modified_time, slang_meaning, slang_name, slang_substitutes, slang_example, category_id )  VALUES (gen_random_uuid(),NOW(),NOW(), '억지 텐션의 줄임말로 기분이 좋지 않음에도 좋은 척을 하는 것을 뜻함','억텐','억지 텐션','오늘 회의에서 걔 완전 억텐이었어.',(SELECT id FROM public.category WHERE category_name = '일상 생활'));
INSERT INTO public.slang ( id, created_time, modified_time, slang_meaning, slang_name, slang_substitutes, slang_example, category_id )  VALUES (gen_random_uuid(),NOW(),NOW(), '점심 메뉴 추천의 줄임말. 점심 메뉴를 추천해달라는 의미','점메추','','오늘 점심 뭐 먹을까? 점메추 좀 해줘.',(SELECT id FROM public.category WHERE category_name = '일상 생활'));
INSERT INTO public.slang ( id, created_time, modified_time, slang_meaning, slang_name, slang_substitutes, slang_example, category_id )  VALUES (gen_random_uuid(),NOW(),NOW(), '완전 내 스타일이라는 뜻','완내스','완전 내 스타일','그 옷 진짜 완내스야.',(SELECT id FROM public.category WHERE category_name = '일상 생활'));
INSERT INTO public.slang ( id, created_time, modified_time, slang_meaning, slang_name, slang_substitutes, slang_example, category_id )  VALUES (gen_random_uuid(),NOW(),NOW(), '혼자서 밥을 먹는 것','혼밥','혼자 밥','오늘은 혼밥으로 간단히 해결했어.',(SELECT id FROM public.category WHERE category_name = '일상 생활'));
INSERT INTO public.slang ( id, created_time, modified_time, slang_meaning, slang_name, slang_substitutes, slang_example, category_id )  VALUES (gen_random_uuid(),NOW(),NOW(), '혼자서 술을 마시는 것','혼술','혼자 술','주말에는 혼술을 즐기는 편이야.',(SELECT id FROM public.category WHERE category_name = '일상 생활'));
INSERT INTO public.slang ( id, created_time, modified_time, slang_meaning, slang_name, slang_substitutes, slang_example, category_id )  VALUES (gen_random_uuid(),NOW(),NOW(), '일과 삶의 균형','워라밸','일과 삶의 균형','요즘 워라밸이 중요하다고 느껴.',(SELECT id FROM public.category WHERE category_name = '직장/학교'));
INSERT INTO public.slang ( id, created_time, modified_time, slang_meaning, slang_name, slang_substitutes, slang_example, category_id )  VALUES (gen_random_uuid(),NOW(),NOW(), '개인의 경력이나 자격','스펙','자격','스펙을 쌓기 위해 다양한 경험을 하고 있어.',(SELECT id FROM public.category WHERE category_name = '직장/학교'));
INSERT INTO public.slang ( id, created_time, modified_time, slang_meaning, slang_name, slang_substitutes, slang_example, category_id )  VALUES (gen_random_uuid(),NOW(),NOW(), '연애로 발전하기 전의 애매한 관계','썸','애매한 관계','그 친구와 썸 타는 중이야.',(SELECT id FROM public.category WHERE category_name = '연애/관계'));
INSERT INTO public.slang ( id, created_time, modified_time, slang_meaning, slang_name, slang_substitutes, slang_example, category_id )  VALUES (gen_random_uuid(),NOW(),NOW(), '사회적 관계가 넓은 사람','인싸','아싸의 반대','그는 인싸라서 항상 사람들과 어울려.',(SELECT id FROM public.category WHERE category_name = '연애/관계'));
INSERT INTO public.slang ( id, created_time, modified_time, slang_meaning, slang_name, slang_substitutes, slang_example, category_id )  VALUES (gen_random_uuid(),NOW(),NOW(), '짧은 동영상이나 이미지','짤','GIF','그 짤 너무 웃겨서 계속 보고 있어.',(SELECT id FROM public.category WHERE category_name = '디지털/인터넷'));
INSERT INTO public.slang ( id, created_time, modified_time, slang_meaning, slang_name, slang_substitutes, slang_example, category_id )  VALUES (gen_random_uuid(),NOW(),NOW(), '자신이 찍은 사진','셀카','자기 사진','오늘 셀카를 많이 찍었어.',(SELECT id FROM public.category WHERE category_name = '디지털/인터넷'));
INSERT INTO public.slang ( id, created_time, modified_time, slang_meaning, slang_name, slang_substitutes, slang_example, category_id )  VALUES (gen_random_uuid(),NOW(),NOW(), '패션에 관심이 많은 사람','패피','패션 피플','그녀는 진정한 패피야.',(SELECT id FROM public.category WHERE category_name = '유행/패션'));
INSERT INTO public.slang ( id, created_time, modified_time, slang_meaning, slang_name, slang_substitutes, slang_example, category_id )  VALUES (gen_random_uuid(),NOW(),NOW(), '독특한 취향을 가진 사람','힙스터','트렌디한 사람','그는 힙스터라서 항상 새로운 트렌드를 따라.',(SELECT id FROM public.category WHERE category_name = '유행/패션'));
INSERT INTO public.slang ( id, created_time, modified_time, slang_meaning, slang_name, slang_substitutes, slang_example, category_id )  VALUES (gen_random_uuid(),NOW(),NOW(), '불안한 상태','불안장애','불안','불안장애로 상담을 받기로 했어.',(SELECT id FROM public.category WHERE category_name = '감정/상태'));
INSERT INTO public.slang ( id, created_time, modified_time, slang_meaning, slang_name, slang_substitutes, slang_example, category_id )  VALUES (gen_random_uuid(),NOW(),NOW(), '가격 대비 심리적 만족','가심비','가격 대비 만족','이 제품은 가심비가 좋아서 구매했어.',(SELECT id FROM public.category WHERE category_name = '소비/경제'));
INSERT INTO public.slang ( id, created_time, modified_time, slang_meaning, slang_name, slang_substitutes, slang_example, category_id )  VALUES (gen_random_uuid(),NOW(),NOW(), '소소하지만 확실한 행복','소확행','작은 행복','소확행을 느끼며 작은 것들에 감사해.',(SELECT id FROM public.category WHERE category_name = '소비/경제'));
INSERT INTO public.slang ( id, created_time, modified_time, slang_meaning, slang_name, slang_substitutes, slang_example, category_id )  VALUES (gen_random_uuid(),NOW(),NOW(), '음식을 먹는 방송','먹방','음식 방송','요즘 먹방을 보면서 식욕이 돋아.',(SELECT id FROM public.category WHERE category_name = '음식/취미'));
INSERT INTO public.slang ( id, created_time, modified_time, slang_meaning, slang_name, slang_substitutes, slang_example, category_id )  VALUES (gen_random_uuid(),NOW(),NOW(), '요리를 하는 방송','쿡방','요리 방송','쿡방을 보며 요리하는 재미를 느껴.',(SELECT id FROM public.category WHERE category_name = '음식/취미'));
INSERT INTO public.slang ( id, created_time, modified_time, slang_meaning, slang_name, slang_substitutes, slang_example, category_id )  VALUES (gen_random_uuid(),NOW(),NOW(), '뇌가 섹시한 남자','뇌섹남','똑똑한 남자','그는 뇌섹남이라서 매력적이야.',(SELECT id FROM public.category WHERE category_name = '기타'));
INSERT INTO public.slang ( id, created_time, modified_time, slang_meaning, slang_name, slang_substitutes, slang_example, category_id )  VALUES (gen_random_uuid(),NOW(),NOW(), '뇌가 섹시한 여자','뇌섹녀','똑똑한 여자','그녀는 뇌섹녀라서 대화가 즐거워.',(SELECT id FROM public.category WHERE category_name = '기타'));
INSERT INTO public.slang ( id, created_time, modified_time, slang_meaning, slang_name, slang_substitutes, slang_example, category_id )  VALUES (gen_random_uuid(),NOW(),NOW(), '국가의 평화로운 상태','국평','평화','국평이 유지되면 모두가 행복해요.',(SELECT id FROM public.category WHERE category_name = '직장/학교'));
INSERT INTO public.slang ( id, created_time, modified_time, slang_meaning, slang_name, slang_substitutes, slang_example, category_id )  VALUES (gen_random_uuid(),NOW(),NOW(), '내일 봬요, 누가?','내봬누','내일 만나요','내봬누, 내일 수업에서 만나요!',(SELECT id FROM public.category WHERE category_name = '직장/학교'));
INSERT INTO public.slang ( id, created_time, modified_time, slang_meaning, slang_name, slang_substitutes, slang_example, category_id )  VALUES (gen_random_uuid(),NOW(),NOW(), '당연히 모르는 치킨','당모치','기본 상식','이건 당모치지, 다들 알잖아?',(SELECT id FROM public.category WHERE category_name = '직장/학교'));
INSERT INTO public.slang ( id, created_time, modified_time, slang_meaning, slang_name, slang_substitutes, slang_example, category_id )  VALUES (gen_random_uuid(),NOW(),NOW(), '알차고 잘 딱 깔끔하게 센스 있는','알잘딱깔센','효율적인 작업','알잘딱깔센으로 보고서를 작성했어요.',(SELECT id FROM public.category WHERE category_name = '직장/학교'));
INSERT INTO public.slang ( id, created_time, modified_time, slang_meaning, slang_name, slang_substitutes, slang_example, category_id )  VALUES (gen_random_uuid(),NOW(),NOW(), '도무지 황당한 차림','돔황챠','엉뚱한 복장','오늘은 돔황챠로 출근했어요.',(SELECT id FROM public.category WHERE category_name = '직장/학교'));
INSERT INTO public.slang ( id, created_time, modified_time, slang_meaning, slang_name, slang_substitutes, slang_example, category_id )  VALUES (gen_random_uuid(),NOW(),NOW(), '식사 집합사, 점심시간에 모임','식집사','점심 모임','점심시간에 식집사 할까요?',(SELECT id FROM public.category WHERE category_name = '직장/학교'));
INSERT INTO public.slang ( id, created_time, modified_time, slang_meaning, slang_name, slang_substitutes, slang_example, category_id )  VALUES (gen_random_uuid(),NOW(),NOW(), '주말 불태우기, 주말에 열심히 놀기','주불','주말 활동','주불로 친구들과 놀러 갔어요.',(SELECT id FROM public.category WHERE category_name = '직장/학교'));
INSERT INTO public.slang ( id, created_time, modified_time, slang_meaning, slang_name, slang_substitutes, slang_example, category_id )  VALUES (gen_random_uuid(),NOW(),NOW(), '하이 워크 얼리버드, 일찍 출근하는 사람','H워얼v','조기 출근자','H워얼v로 출근하면 좋겠어요.',(SELECT id FROM public.category WHERE category_name = '직장/학교'));
INSERT INTO public.slang ( id, created_time, modified_time, slang_meaning, slang_name, slang_substitutes, slang_example, category_id )  VALUES (gen_random_uuid(),NOW(),NOW(), '고백 중간, 고백을 하려는 중','ㄱㅂㅈㄱ','고백 준비','ㄱㅂㅈㄱ, 나도 고백할까?',(SELECT id FROM public.category WHERE category_name = '직장/학교'));
INSERT INTO public.slang ( id, created_time, modified_time, slang_meaning, slang_name, slang_substitutes, slang_example, category_id )  VALUES (gen_random_uuid(),NOW(),NOW(), '이직 후 백수, 이직 후 일자리가 없는 상태','이퇴백','이직 후 실업','이퇴백이라서 고민 중이에요.',(SELECT id FROM public.category WHERE category_name = '직장/학교'));
INSERT INTO public.slang ( id, created_time, modified_time, slang_meaning, slang_name, slang_substitutes, slang_example, category_id )  VALUES (gen_random_uuid(),NOW(),NOW(), '농담 협의 은행, 농담을 주고받는 곳','농협은행','유머 회의','농협은행에서 농담을 나눴어요.',(SELECT id FROM public.category WHERE category_name = '직장/학교'));
INSERT INTO public.slang ( id, created_time, modified_time, slang_meaning, slang_name, slang_substitutes, slang_example, category_id )  VALUES (gen_random_uuid(),NOW(),NOW(), '이 생은 망했어, 상황이 좋지 않음','이생망','절망','이생망이라서 힘들어요.',(SELECT id FROM public.category WHERE category_name = '직장/학교'));
INSERT INTO public.slang ( id, created_time, modified_time, slang_meaning, slang_name, slang_substitutes, slang_example, category_id )  VALUES (gen_random_uuid(),NOW(),NOW(), '선배님(SBN)을 의미하는 말','SBN','선배님','SBN을 통해 많은 것을 배웠어요.',(SELECT id FROM public.category WHERE category_name = '직장/학교'));
INSERT INTO public.slang ( id, created_time, modified_time, slang_meaning, slang_name, slang_substitutes, slang_example, category_id )  VALUES (gen_random_uuid(),NOW(),NOW(), '혼자 있는 틈, 혼자만의 시간','혼틈','개인 시간','혼틈을 즐기며 책을 읽었어요.',(SELECT id FROM public.category WHERE category_name = '직장/학교'));
INSERT INTO public.slang ( id, created_time, modified_time, slang_meaning, slang_name, slang_substitutes, slang_example, category_id )  VALUES (gen_random_uuid(),NOW(),NOW(), '팬과 아저씨의 조합, 팬이 많은 아저씨','팬아저','인기 있는 사람','팬아저로 유명한 분이세요.',(SELECT id FROM public.category WHERE category_name = '직장/학교'));
INSERT INTO public.slang ( id, created_time, modified_time, slang_meaning, slang_name, slang_substitutes, slang_example, category_id )  VALUES (gen_random_uuid(),NOW(),NOW(), '갑자기 통화 알림, 갑자기 전화가 오는 것','갑통알','급한 전화','갑통알이 와서 놀랐어요.',(SELECT id FROM public.category WHERE category_name = '직장/학교'));
INSERT INTO public.slang ( id, created_time, modified_time, slang_meaning, slang_name, slang_substitutes, slang_example, category_id )  VALUES (gen_random_uuid(),NOW(),NOW(), '연인 사이로 발전하기 전의 미묘한 관계','썸','애매한 관계','"우리 아직 사귀는 건 아닌데, 썸 타는 중이야."',(SELECT id FROM public.category WHERE category_name = '연애'));
INSERT INTO public.slang ( id, created_time, modified_time, slang_meaning, slang_name, slang_substitutes, slang_example, category_id )  VALUES (gen_random_uuid(),NOW(),NOW(), '관심을 주었다가 뺐었다 하며 상대의 마음을 떠보는 행동','밀당','심리전','"밀당의 고수는 상대를 애타게 만들지."',(SELECT id FROM public.category WHERE category_name = '연애'));
INSERT INTO public.slang ( id, created_time, modified_time, slang_meaning, slang_name, slang_substitutes, slang_example, category_id )  VALUES (gen_random_uuid(),NOW(),NOW(), '강아지처럼 귀엽고 순수한 매력','댕댕미','순수한 매력','"너는 댕댕미가 넘쳐서 주변에서 좋아하잖아!"',(SELECT id FROM public.category WHERE category_name = '연애'));
INSERT INTO public.slang ( id, created_time, modified_time, slang_meaning, slang_name, slang_substitutes, slang_example, category_id )  VALUES (gen_random_uuid(),NOW(),NOW(), '심장이 쿵 내려앉을 정도로 설렘을 느낌','심쿵','설렘','"그 사람 미소에 완전 심쿵했어!"',(SELECT id FROM public.category WHERE category_name = '연애'));
INSERT INTO public.slang ( id, created_time, modified_time, slang_meaning, slang_name, slang_substitutes, slang_example, category_id )  VALUES (gen_random_uuid(),NOW(),NOW(), '돌려 말하지 않고 직설적으로 표현하는 태도','돌직구','직설화법','"갑자기 고백이라니, 돌직구 던지네!"',(SELECT id FROM public.category WHERE category_name = '연애'));
INSERT INTO public.slang ( id, created_time, modified_time, slang_meaning, slang_name, slang_substitutes, slang_example, category_id )  VALUES (gen_random_uuid(),NOW(),NOW(), '금방 사랑에 빠지는 사람','금사빠','감성적인 사람','"나 완전 금사빠라서 자주 설레."',(SELECT id FROM public.category WHERE category_name = '연애'));
INSERT INTO public.slang ( id, created_time, modified_time, slang_meaning, slang_name, slang_substitutes, slang_example, category_id )  VALUES (gen_random_uuid(),NOW(),NOW(), '열심히 공부하는 것','빡공','열공','"이번 시험 때문에 빡공 중이야."',(SELECT id FROM public.category WHERE category_name = '학교'));
INSERT INTO public.slang ( id, created_time, modified_time, slang_meaning, slang_name, slang_substitutes, slang_example, category_id )  VALUES (gen_random_uuid(),NOW(),NOW(), '참여하지 않고 보기만 하는 것','눈팅','관망','"단톡방에서 맨날 눈팅만 하네?"',(SELECT id FROM public.category WHERE category_name = '학교'));
INSERT INTO public.slang ( id, created_time, modified_time, slang_meaning, slang_name, slang_substitutes, slang_example, category_id )  VALUES (gen_random_uuid(),NOW(),NOW(), '학교폭력의 줄임말','학폭','학교 내 폭력','"학폭 사건은 절대 가볍게 넘어가면 안 돼."',(SELECT id FROM public.category WHERE category_name = '학교'));
INSERT INTO public.slang ( id, created_time, modified_time, slang_meaning, slang_name, slang_substitutes, slang_example, category_id )  VALUES (gen_random_uuid(),NOW(),NOW(), '이야기나 경험담을 의미함','썰','이야기','"어제 들은 썰이 있는데 완전 대박이야."',(SELECT id FROM public.category WHERE category_name = '학교'));
INSERT INTO public.slang ( id, created_time, modified_time, slang_meaning, slang_name, slang_substitutes, slang_example, category_id )  VALUES (gen_random_uuid(),NOW(),NOW(), '돈을 쓰는 재미를 뜻하는 말','탕진잼','소비의 즐거움','"이번 달 월급 탕진잼 해버렸어."',(SELECT id FROM public.category WHERE category_name = '연애'));
INSERT INTO public.slang ( id, created_time, modified_time, slang_meaning, slang_name, slang_substitutes, slang_example, category_id )  VALUES (gen_random_uuid(),NOW(),NOW(), '너무 빨리 탈락하는 것','광탈','즉시 탈락','"소개팅했는데 광탈했어 ㅠㅠ"',(SELECT id FROM public.category WHERE category_name = '연애'));
INSERT INTO public.slang ( id, created_time, modified_time, slang_meaning, slang_name, slang_substitutes, slang_example, category_id )  VALUES (gen_random_uuid(),NOW(),NOW(), '사람마다 다르다는 의미','사바사','개인 차이','"연애 스타일은 사바사야."',(SELECT id FROM public.category WHERE category_name = '연애'));
INSERT INTO public.slang ( id, created_time, modified_time, slang_meaning, slang_name, slang_substitutes, slang_example, category_id )  VALUES (gen_random_uuid(),NOW(),NOW(), '연애 감정을 표현하는 행동','플러팅','유혹','"그 사람 나한테 플러팅하는 것 같아!"',(SELECT id FROM public.category WHERE category_name = '연애'));
INSERT INTO public.slang ( id, created_time, modified_time, slang_meaning, slang_name, slang_substitutes, slang_example, category_id )  VALUES (gen_random_uuid(),NOW(),NOW(), '고백하기 좋은 타이밍','고백각','고백 찬스','"이 분위기면 고백각 아닌가?"',(SELECT id FROM public.category WHERE category_name = '연애'));
INSERT INTO public.slang ( id, created_time, modified_time, slang_meaning, slang_name, slang_substitutes, slang_example, category_id )  VALUES (gen_random_uuid(),NOW(),NOW(), '꾸민 듯 안 꾸민 스타일','꾸안꾸','내추럴 시크','"오늘 꾸안꾸 느낌으로 입었어!"',(SELECT id FROM public.category WHERE category_name = '유행/패션'));
INSERT INTO public.slang ( id, created_time, modified_time, slang_meaning, slang_name, slang_substitutes, slang_example, category_id )  VALUES (gen_random_uuid(),NOW(),NOW(), '트렌디하고 개성 있는 스타일','힙하다','트렌디하다','"저 친구 스타일 완전 힙하다!"',(SELECT id FROM public.category WHERE category_name = '유행/패션'));
INSERT INTO public.slang ( id, created_time, modified_time, slang_meaning, slang_name, slang_substitutes, slang_example, category_id )  VALUES (gen_random_uuid(),NOW(),NOW(), '같은 옷을 다양한 스타일로 연출하는 것','돌려 입기','스타일 변형','"돌려 입기 잘하면 옷 많이 안 사도 돼."',(SELECT id FROM public.category WHERE category_name = '유행/패션'));
INSERT INTO public.slang ( id, created_time, modified_time, slang_meaning, slang_name, slang_substitutes, slang_example, category_id )  VALUES (gen_random_uuid(),NOW(),NOW(), '꾸미고 꾸미고 또 꾸민 스타일','꾸꾸꾸','풀착장','"오늘 파티니까 꾸꾸꾸 스타일로 가야지!"',(SELECT id FROM public.category WHERE category_name = '유행/패션'));
INSERT INTO public.slang ( id, created_time, modified_time, slang_meaning, slang_name, slang_substitutes, slang_example, category_id )  VALUES (gen_random_uuid(),NOW(),NOW(), '단순하고 심플한 스타일의 패션','미니멀룩','심플룩','"미니멀룩 좋아해서 베이직한 옷만 사."',(SELECT id FROM public.category WHERE category_name = '유행/패션'));
INSERT INTO public.slang ( id, created_time, modified_time, slang_meaning, slang_name, slang_substitutes, slang_example, category_id )  VALUES (gen_random_uuid(),NOW(),NOW(), '화려하고 개성 있는 스타일의 패션','맥시멀룩','과장된 스타일','"맥시멀룩은 색깔 조합이 중요해!"',(SELECT id FROM public.category WHERE category_name = '유행/패션'));
INSERT INTO public.slang ( id, created_time, modified_time, slang_meaning, slang_name, slang_substitutes, slang_example, category_id )  VALUES (gen_random_uuid(),NOW(),NOW(), '90~00년대 미국 하이틴 영화 스타일','하이틴룩','레트로 하이틴','"하이틴룩 하면 체크 스커트가 빠질 수 없지."',(SELECT id FROM public.category WHERE category_name = '유행/패션'));
INSERT INTO public.slang ( id, created_time, modified_time, slang_meaning, slang_name, slang_substitutes, slang_example, category_id )  VALUES (gen_random_uuid(),NOW(),NOW(), '톡톡 튀고 귀여운 개성을 강조한 패션','키치룩','유니크룩','"오늘 키치룩 도전해봤어, 어때?"',(SELECT id FROM public.category WHERE category_name = '유행/패션'));
INSERT INTO public.slang ( id, created_time, modified_time, slang_meaning, slang_name, slang_substitutes, slang_example, category_id )  VALUES (gen_random_uuid(),NOW(),NOW(), '코로나 이후 등장한 새로운 스타일','엔데믹 패션','포스트 코로나룩','"요즘 엔데믹 패션으로 마스크 끼는 사람 줄었어."',(SELECT id FROM public.category WHERE category_name = '유행/패션'));
INSERT INTO public.slang ( id, created_time, modified_time, slang_meaning, slang_name, slang_substitutes, slang_example, category_id )  VALUES (gen_random_uuid(),NOW(),NOW(), '집 근처 외출용 편안한 패션','원마일웨어','간편 외출룩','"카페 가니까 다들 원마일웨어 입었더라."',(SELECT id FROM public.category WHERE category_name = '유행/패션'));
INSERT INTO public.slang ( id, created_time, modified_time, slang_meaning, slang_name, slang_substitutes, slang_example, category_id )  VALUES (gen_random_uuid(),NOW(),NOW(), '2000년대 초반 스타일이 다시 유행하는 것','Y2K 패션','2000년대 레트로룩','"Y2K 패션엔 크롭티랑 와이드 팬츠가 필수지!"',(SELECT id FROM public.category WHERE category_name = '유행/패션'));
INSERT INTO public.slang ( id, created_time, modified_time, slang_meaning, slang_name, slang_substitutes, slang_example, category_id )  VALUES (gen_random_uuid(),NOW(),NOW(), '특정 컨셉을 강조한 패션 스타일','코어룩','컨셉 패션','"고프코어룩은 기능성 옷을 멋지게 입는 거야."',(SELECT id FROM public.category WHERE category_name = '유행/패션'));
INSERT INTO public.slang ( id, created_time, modified_time, slang_meaning, slang_name, slang_substitutes, slang_example, category_id )  VALUES (gen_random_uuid(),NOW(),NOW(), '톤 다운된 차분한 색상 계열','뮤트톤','차분한 색감','"오늘 뮤트톤으로 맞춰 입었더니 차분해 보여."',(SELECT id FROM public.category WHERE category_name = '유행/패션'));
INSERT INTO public.slang ( id, created_time, modified_time, slang_meaning, slang_name, slang_substitutes, slang_example, category_id )  VALUES (gen_random_uuid(),NOW(),NOW(), '피부톤과 어울리지 않는 색상을 입는 것','톤그로','색상 불일치','"톤그로 심한 색 입으면 얼굴이 떠보여."',(SELECT id FROM public.category WHERE category_name = '유행/패션'));
INSERT INTO public.slang ( id, created_time, modified_time, slang_meaning, slang_name, slang_substitutes, slang_example, category_id )  VALUES (gen_random_uuid(),NOW(),NOW(), '패션을 돋보이게 하는 방법','스타일링 꿀팁','패션 노하우','"가을엔 레이어드가 스타일링 꿀팁이야."',(SELECT id FROM public.category WHERE category_name = '유행/패션'));
INSERT INTO public.slang ( id, created_time, modified_time, slang_meaning, slang_name, slang_substitutes, slang_example, category_id )  VALUES (gen_random_uuid(),NOW(),NOW(), '아무 때나 편하게 입을 수 있는 옷','휘뚜루마뚜루','만능','"이 바지는 휘뚜루마뚜루라서 매일 입어."',(SELECT id FROM public.category WHERE category_name = '유행/패션'));