INSERT INTO public.category (id, category_name) VALUES
(1, '일상생활'),
(2, '직장/학교'),
(3, '연애/관계'),
(4, '디지털/인터넷'),
(5, '유행/패션'),
(6, '감정/상태'),
(7, '소비/경제'),
(8, '정치/사회'),
(9, '음식/취미'),
(10, '기타');

INSERT INTO public.slang ( id, created_time, modified_time, slang_meaning, slang_name, slang_substitutes, slang_example, category_id )  VALUES (gen_random_uuid(),NOW(),NOW(), '인기 있는 사람','인싸','인기쟁이','우리 반에서 제일 인싸는 민수야.',(SELECT id FROM public.category WHERE category_name = '디지털/인터넷'));
INSERT INTO public.slang ( id, created_time, modified_time, slang_meaning, slang_name, slang_substitutes, slang_example, category_id )  VALUES (gen_random_uuid(),NOW(),NOW(), '집단 내에서 소외되어 있거나 적극적으로 어울리지 않는 사람을 이르는 말','아싸','외톨이','나는 대학교에서 아싸라서 과제를 혼자해야해.',(SELECT id FROM public.category WHERE category_name = '디지털/인터넷'));
INSERT INTO public.slang ( id, created_time, modified_time, slang_meaning, slang_name, slang_substitutes, slang_example, category_id )  VALUES (gen_random_uuid(),NOW(),NOW(), '매우 재미있음을 뜻하는 말','꿀잼','매우 재미있는','이번 주말에는 넷플릭스에서 꿀잼 드라마를 봤어.',(SELECT id FROM public.category WHERE category_name = '디지털/인터넷'));
INSERT INTO public.slang ( id, created_time, modified_time, slang_meaning, slang_name, slang_substitutes, slang_example, category_id )  VALUES (gen_random_uuid(),NOW(),NOW(), '재미가 없음을 뜻하는 말','노잼','재미없는','그 영화는 너무 노잼이라서 보다가 잤어.',(SELECT id FROM public.category WHERE category_name = '디지털/인터넷'));
INSERT INTO public.slang ( id, created_time, modified_time, slang_meaning, slang_name, slang_substitutes, slang_example, category_id )  VALUES (gen_random_uuid(),NOW(),NOW(), '매우 힘든 상황에서도 포기하지 않고 버티는 것을 뜻하는 말','존버','인내심 있게 버티기','주식 투자에서 존버하면 수익을 얻을 수 있어.',(SELECT id FROM public.category WHERE category_name = '디지털/인터넷'));
INSERT INTO public.slang ( id, created_time, modified_time, slang_meaning, slang_name, slang_substitutes, slang_example, category_id )  VALUES (gen_random_uuid(),NOW(),NOW(), '취향을 존중한다는 뜻','취존','취향 존중','너의 취미를 취존할게.',(SELECT id FROM public.category WHERE category_name = '디지털/인터넷'));
INSERT INTO public.slang ( id, created_time, modified_time, slang_meaning, slang_name, slang_substitutes, slang_example, category_id )  VALUES (gen_random_uuid(),NOW(),NOW(), '매우 인정한다는 뜻','킹정','매우 인정함','이번 프로젝트는 정말 킹정이야.',(SELECT id FROM public.category WHERE category_name = '디지털/인터넷'));
INSERT INTO public.slang ( id, created_time, modified_time, slang_meaning, slang_name, slang_substitutes, slang_example, category_id )  VALUES (gen_random_uuid(),NOW(),NOW(), '호구처럼 이용당하는 사람을 뜻하는 말','흑우','호구','그 가게는 흑우들만 가는 곳이야.',(SELECT id FROM public.category WHERE category_name = '디지털/인터넷'));
INSERT INTO public.slang ( id, created_time, modified_time, slang_meaning, slang_name, slang_substitutes, slang_example, category_id )  VALUES (gen_random_uuid(),NOW(),NOW(), '엄격, 근엄, 진지하다는 뜻','엄근진','엄격하고 진지한','선생님은 수업 시간에 항상 엄근진하셔.',(SELECT id FROM public.category WHERE category_name = '디지털/인터넷'));
INSERT INTO public.slang ( id, created_time, modified_time, slang_meaning, slang_name, slang_substitutes, slang_example, category_id )  VALUES (gen_random_uuid(),NOW(),NOW(), '꾸민 듯 안 꾸민 듯 자연스러운 스타일을 뜻하는 말','꾸안꾸','자연스러운 스타일','오늘은 꾸안꾸로 입고 왔어.',(SELECT id FROM public.category WHERE category_name = '일상생활'));
INSERT INTO public.slang ( id, created_time, modified_time, slang_meaning, slang_name, slang_substitutes, slang_example, category_id )  VALUES (gen_random_uuid(),NOW(),NOW(), '만나서 반가워 잘 부탁해라는 뜻','만반잘부','만나서 반가워 잘 부탁해','오늘 처음 만난 친구에게 만반잘부라고 인사했어.',(SELECT id FROM public.category WHERE category_name = '일상생활'));
INSERT INTO public.slang ( id, created_time, modified_time, slang_meaning, slang_name, slang_substitutes, slang_example, category_id )  VALUES (gen_random_uuid(),NOW(),NOW(), '스스로 불러온 재앙이라는 뜻','스불재','스스로 자초한 불행','내가 스불재를 당해서 지금 너무 힘들어.',(SELECT id FROM public.category WHERE category_name = '일상생활'));
INSERT INTO public.slang ( id, created_time, modified_time, slang_meaning, slang_name, slang_substitutes, slang_example, category_id )  VALUES (gen_random_uuid(),NOW(),NOW(), '알아서 잘 딱 깔끔하고 센스있게라는 뜻','알잘딱깔센','알아서 잘 처리함','이번 프레젠테이션 준비는 알잘딱깔센하게 했어.',(SELECT id FROM public.category WHERE category_name = '일상생활'));
INSERT INTO public.slang ( id, created_time, modified_time, slang_meaning, slang_name, slang_substitutes, slang_example, category_id )  VALUES (gen_random_uuid(),NOW(),NOW(), '사귀기 전 단계를 뜻하는 말','삼귀자','사귀기 전 단계','우리 이제 삼귀자.',(SELECT id FROM public.category WHERE category_name = '연애/관계'));
INSERT INTO public.slang ( id, created_time, modified_time, slang_meaning, slang_name, slang_substitutes, slang_example, category_id )  VALUES (gen_random_uuid(),NOW(),NOW(), '자연스러운 만남 추구라는 뜻','자만추','자연스러운 만남 추구','나는 자만추가 좋아.',(SELECT id FROM public.category WHERE category_name = '연애/관계'));
INSERT INTO public.slang ( id, created_time, modified_time, slang_meaning, slang_name, slang_substitutes, slang_example, category_id )  VALUES (gen_random_uuid(),NOW(),NOW(), '복잡한 세상 편하게 살자라는 뜻','복세편살','편하게 살기','복세편살하며 살고 싶어.',(SELECT id FROM public.category WHERE category_name = '일상생활'));
INSERT INTO public.slang ( id, created_time, modified_time, slang_meaning, slang_name, slang_substitutes, slang_example, category_id )  VALUES (gen_random_uuid(),NOW(),NOW(), '좋아요 댓글 구독 알림설정의 줄임말','좋댓구알','좋아요, 댓글, 구독, 알림설정','유튜브 영상을 볼 때는 꼭 좋댓구알 해주세요.',(SELECT id FROM public.category WHERE category_name = '일상생활'));
INSERT INTO public.slang ( id, created_time, modified_time, slang_meaning, slang_name, slang_substitutes, slang_example, category_id )  VALUES (gen_random_uuid(),NOW(),NOW(), '억지 텐션의 줄임말로 기분이 좋지 않음에도 좋은 척을 하는 것을 뜻함','억텐','억지 텐션','오늘 회의에서 걔 완전 억텐이었어.',(SELECT id FROM public.category WHERE category_name = '감정/상태'));
INSERT INTO public.slang ( id, created_time, modified_time, slang_meaning, slang_name, slang_substitutes, slang_example, category_id )  VALUES (gen_random_uuid(),NOW(),NOW(), '점심 메뉴 추천의 줄임말. 점심 메뉴를 추천해달라는 의미','점메추','점심 메뉴 추천','오늘 점심 뭐 먹을까? 점메추 좀 해줘.',(SELECT id FROM public.category WHERE category_name = '음식/취미'));
INSERT INTO public.slang ( id, created_time, modified_time, slang_meaning, slang_name, slang_substitutes, slang_example, category_id )  VALUES (gen_random_uuid(),NOW(),NOW(), '완전 내 스타일이라는 뜻','완내스','완전 내 스타일','그 옷 진짜 완내스야.',(SELECT id FROM public.category WHERE category_name = '일상생활'));
INSERT INTO public.slang ( id, created_time, modified_time, slang_meaning, slang_name, slang_substitutes, slang_example, category_id )  VALUES (gen_random_uuid(),NOW(),NOW(), '혼자서 밥을 먹는 것','혼밥','혼자 밥','오늘은 혼밥으로 간단히 해결했어.',(SELECT id FROM public.category WHERE category_name = '음식/취미'));
INSERT INTO public.slang ( id, created_time, modified_time, slang_meaning, slang_name, slang_substitutes, slang_example, category_id )  VALUES (gen_random_uuid(),NOW(),NOW(), '혼자서 술을 마시는 것','혼술','혼자 술','주말에는 혼술을 즐기는 편이야.',(SELECT id FROM public.category WHERE category_name = '음식/취미'));
INSERT INTO public.slang ( id, created_time, modified_time, slang_meaning, slang_name, slang_substitutes, slang_example, category_id )  VALUES (gen_random_uuid(),NOW(),NOW(), '일과 삶의 균형','워라밸','일과 삶의 균형','요즘 워라밸이 중요하다고 느껴.',(SELECT id FROM public.category WHERE category_name = '직장/학교'));
INSERT INTO public.slang ( id, created_time, modified_time, slang_meaning, slang_name, slang_substitutes, slang_example, category_id )  VALUES (gen_random_uuid(),NOW(),NOW(), '개인의 경력이나 자격','스펙','자격','스펙을 쌓기 위해 다양한 경험을 하고 있어.',(SELECT id FROM public.category WHERE category_name = '직장/학교'));
INSERT INTO public.slang ( id, created_time, modified_time, slang_meaning, slang_name, slang_substitutes, slang_example, category_id )  VALUES (gen_random_uuid(),NOW(),NOW(), '연애로 발전하기 전의 애매한 관계','썸','애매한 관계','그 친구와 썸 타는 중이야.',(SELECT id FROM public.category WHERE category_name = '연애/관계'));
INSERT INTO public.slang ( id, created_time, modified_time, slang_meaning, slang_name, slang_substitutes, slang_example, category_id )  VALUES (gen_random_uuid(),NOW(),NOW(), '짧은 동영상이나 이미지','짤','GIF','그 짤 너무 웃겨서 계속 보고 있어.',(SELECT id FROM public.category WHERE category_name = '디지털/인터넷'));
INSERT INTO public.slang ( id, created_time, modified_time, slang_meaning, slang_name, slang_substitutes, slang_example, category_id )  VALUES (gen_random_uuid(),NOW(),NOW(), '자신이 찍은 사진','셀카','자기 사진','오늘 셀카를 많이 찍었어.',(SELECT id FROM public.category WHERE category_name = '디지털/인터넷'));
INSERT INTO public.slang ( id, created_time, modified_time, slang_meaning, slang_name, slang_substitutes, slang_example, category_id )  VALUES (gen_random_uuid(),NOW(),NOW(), '패션에 관심이 많은 사람','패피','패션 피플','그녀는 진정한 패피야.',(SELECT id FROM public.category WHERE category_name = '유행/패션'));
INSERT INTO public.slang ( id, created_time, modified_time, slang_meaning, slang_name, slang_substitutes, slang_example, category_id )  VALUES (gen_random_uuid(),NOW(),NOW(), '1940년대의 재즈광들을 지칭하는 슬랭에서 유래한 말로 1990년대 이후 독특한 문화적 코드를 공유하는 젊은이를 칭하는 말','힙스터','트렌디한 사람','그는 힙스터라서 항상 새로운 트렌드를 따라.',(SELECT id FROM public.category WHERE category_name = '유행/패션'));
INSERT INTO public.slang ( id, created_time, modified_time, slang_meaning, slang_name, slang_substitutes, slang_example, category_id )  VALUES (gen_random_uuid(),NOW(),NOW(), '소소하지만 확실한 행복','소확행','작은 행복','소확행을 느끼며 작은 것들에 감사해.',(SELECT id FROM public.category WHERE category_name = '소비/경제'));
INSERT INTO public.slang ( id, created_time, modified_time, slang_meaning, slang_name, slang_substitutes, slang_example, category_id )  VALUES (gen_random_uuid(),NOW(),NOW(), '음식을 먹는 방송','먹방','음식 방송','요즘 먹방을 보면서 식욕이 돋아.',(SELECT id FROM public.category WHERE category_name = '음식/취미'));
INSERT INTO public.slang ( id, created_time, modified_time, slang_meaning, slang_name, slang_substitutes, slang_example, category_id )  VALUES (gen_random_uuid(),NOW(),NOW(), '요리를 하는 방송','쿡방','요리 방송','쿡방을 보며 요리하는 재미를 느껴.',(SELECT id FROM public.category WHERE category_name = '음식/취미'));
INSERT INTO public.slang ( id, created_time, modified_time, slang_meaning, slang_name, slang_substitutes, slang_example, category_id )  VALUES (gen_random_uuid(),NOW(),NOW(), '뇌가 섹시한 남자의 줄임말로 똑똑한 남자를 의미','뇌섹남','똑똑한 남자','그는 뇌섹남이라서 매력적이야.',(SELECT id FROM public.category WHERE category_name = '기타'));
INSERT INTO public.slang ( id, created_time, modified_time, slang_meaning, slang_name, slang_substitutes, slang_example, category_id )  VALUES (gen_random_uuid(),NOW(),NOW(), '뇌가 섹시한 여자의 줄임말로 똑똑한 여자를 의미','뇌섹녀','똑똑한 여자','그녀는 뇌섹녀라서 대화가 즐거워.',(SELECT id FROM public.category WHERE category_name = '기타'));
INSERT INTO public.slang ( id, created_time, modified_time, slang_meaning, slang_name, slang_substitutes, slang_example, category_id )  VALUES (gen_random_uuid(),NOW(),NOW(), '"도망쳐"를 빠르게 발음한 신조어','돔황챠','도망치다','엄마가 그릇 깬 사람 찾고 있어, 빨리 돔황챠!',(SELECT id FROM public.category WHERE category_name = '직장/학교'));
INSERT INTO public.slang ( id, created_time, modified_time, slang_meaning, slang_name, slang_substitutes, slang_example, category_id )  VALUES (gen_random_uuid(),NOW(),NOW(), '"식물 + 집사"의 합성어로, 식물을 키우면서 보살피는 사람을 뜻','식집사','가드너','식집사들은 성격이 온화한거 같아',(SELECT id FROM public.category WHERE category_name = '직장/학교'));
INSERT INTO public.slang ( id, created_time, modified_time, slang_meaning, slang_name, slang_substitutes, slang_example, category_id )  VALUES (gen_random_uuid(),NOW(),NOW(), '"너무예쁘다"라는 의미로 사용되는 신조어.','농협은행','너무 예뻐','농협은행에서 농담을 나눴어요.',(SELECT id FROM public.category WHERE category_name = '직장/학교'));
INSERT INTO public.slang ( id, created_time, modified_time, slang_meaning, slang_name, slang_substitutes, slang_example, category_id )  VALUES (gen_random_uuid(),NOW(),NOW(), '이번 생은 망했어의 줄임말, 상황이 좋지 않음을 의미','이생망','절망','이생망이라서 힘들어요.',(SELECT id FROM public.category WHERE category_name = '직장/학교'));
INSERT INTO public.slang ( id, created_time, modified_time, slang_meaning, slang_name, slang_substitutes, slang_example, category_id )  VALUES (gen_random_uuid(),NOW(),NOW(), '선배님(SBN)을 의미하는 말','SBN','선배님','SBN을 통해 많은 것을 배웠어요.',(SELECT id FROM public.category WHERE category_name = '직장/학교'));
INSERT INTO public.slang ( id, created_time, modified_time, slang_meaning, slang_name, slang_substitutes, slang_example, category_id )  VALUES (gen_random_uuid(),NOW(),NOW(), '특별히 팬은 아니지만, 너무 멋지거나 예뻐서 사진이나 영상을 저장하는 것','팬아저','인기 있는 사람','팬아저로 유명한 분이세요.',(SELECT id FROM public.category WHERE category_name = '디지털/인터넷'));
INSERT INTO public.slang ( id, created_time, modified_time, slang_meaning, slang_name, slang_substitutes, slang_example, category_id )  VALUES (gen_random_uuid(),NOW(),NOW(), '관심을 주었다가 뺐었다 하며 상대의 마음을 떠보는 행동','밀당','심리전','밀당의 고수는 상대를 애타게 만들지.',(SELECT id FROM public.category WHERE category_name = '연애/관계'));
INSERT INTO public.slang ( id, created_time, modified_time, slang_meaning, slang_name, slang_substitutes, slang_example, category_id )  VALUES (gen_random_uuid(),NOW(),NOW(), '강아지처럼 귀엽고 순수한 매력','댕댕미','순수한 매력','너는 댕댕미가 넘쳐서 주변에서 좋아하잖아!',(SELECT id FROM public.category WHERE category_name = '연애/관계'));
INSERT INTO public.slang ( id, created_time, modified_time, slang_meaning, slang_name, slang_substitutes, slang_example, category_id )  VALUES (gen_random_uuid(),NOW(),NOW(), '심장이 쿵 내려앉을 정도로 설렘을 느낌','심쿵','설렘','그 사람 미소에 완전 심쿵했어!',(SELECT id FROM public.category WHERE category_name = '연애/관계'));
INSERT INTO public.slang ( id, created_time, modified_time, slang_meaning, slang_name, slang_substitutes, slang_example, category_id )  VALUES (gen_random_uuid(),NOW(),NOW(), '돌려 말하지 않고 직설적으로 표현하는 태도','돌직구','직설화법','갑자기 고백이라니, 돌직구 던지네!',(SELECT id FROM public.category WHERE category_name = '연애/관계'));
INSERT INTO public.slang ( id, created_time, modified_time, slang_meaning, slang_name, slang_substitutes, slang_example, category_id )  VALUES (gen_random_uuid(),NOW(),NOW(), '금방 사랑에 빠지는 사람','금사빠','감성적인 사람','나 완전 금사빠라서 자주 설레.',(SELECT id FROM public.category WHERE category_name = '연애/관계'));
INSERT INTO public.slang ( id, created_time, modified_time, slang_meaning, slang_name, slang_substitutes, slang_example, category_id )  VALUES (gen_random_uuid(),NOW(),NOW(), '열심히 공부하는 것','빡공','열공','이번 시험 때문에 빡공 중이야.',(SELECT id FROM public.category WHERE category_name = '학교'));
INSERT INTO public.slang ( id, created_time, modified_time, slang_meaning, slang_name, slang_substitutes, slang_example, category_id )  VALUES (gen_random_uuid(),NOW(),NOW(), '참여하지 않고 보기만 하는 것','눈팅','관망','단톡방에서 맨날 눈팅만 하네?',(SELECT id FROM public.category WHERE category_name = '디지털/인터넷'));
INSERT INTO public.slang ( id, created_time, modified_time, slang_meaning, slang_name, slang_substitutes, slang_example, category_id )  VALUES (gen_random_uuid(),NOW(),NOW(), '이야기나 경험담을 의미함','썰','이야기','어제 들은 썰이 있는데 완전 대박이야.',(SELECT id FROM public.category WHERE category_name = '학교'));
INSERT INTO public.slang ( id, created_time, modified_time, slang_meaning, slang_name, slang_substitutes, slang_example, category_id )  VALUES (gen_random_uuid(),NOW(),NOW(), '돈을 쓰는 재미를 뜻하는 말','탕진잼','소비의 즐거움','이번 달 월급 탕진잼 해버렸어.',(SELECT id FROM public.category WHERE category_name = '연애/관계'));
INSERT INTO public.slang ( id, created_time, modified_time, slang_meaning, slang_name, slang_substitutes, slang_example, category_id )  VALUES (gen_random_uuid(),NOW(),NOW(), '빠른 속도로 탈락하는 것 ','광탈','즉시 탈락','뮤지컬 티켓팅 광탈했어 ㅠㅠ',(SELECT id FROM public.category WHERE category_name = '연애/관계'));
INSERT INTO public.slang ( id, created_time, modified_time, slang_meaning, slang_name, slang_substitutes, slang_example, category_id )  VALUES (gen_random_uuid(),NOW(),NOW(), '사람 바이 사람의 줄임말로 사람마다 다르다는 의미','사바사','개인 차이','연애 스타일은 사바사야.',(SELECT id FROM public.category WHERE category_name = '일상생활'));
INSERT INTO public.slang ( id, created_time, modified_time, slang_meaning, slang_name, slang_substitutes, slang_example, category_id )  VALUES (gen_random_uuid(),NOW(),NOW(), '이성에게 호감을 표현하는 가벼운 밀당이나 끼부림','플러팅','유혹','그 사람 나한테 플러팅하는 것 같아!',(SELECT id FROM public.category WHERE category_name = '연애/관계'));
INSERT INTO public.slang ( id, created_time, modified_time, slang_meaning, slang_name, slang_substitutes, slang_example, category_id )  VALUES (gen_random_uuid(),NOW(),NOW(), '고백하기 좋은 타이밍','고백각','고백 찬스','이 분위기면 고백각 아닌가?',(SELECT id FROM public.category WHERE category_name = '연애/관계'));
INSERT INTO public.slang ( id, created_time, modified_time, slang_meaning, slang_name, slang_substitutes, slang_example, category_id )  VALUES (gen_random_uuid(),NOW(),NOW(), '꾸민 듯 안 꾸민 스타일을 의미','꾸안꾸','자연스러운 스타일','오늘 꾸안꾸 느낌으로 입었어!',(SELECT id FROM public.category WHERE category_name = '유행/패션'));
INSERT INTO public.slang ( id, created_time, modified_time, slang_meaning, slang_name, slang_substitutes, slang_example, category_id )  VALUES (gen_random_uuid(),NOW(),NOW(), '꾸미고 꾸미고 또 꾸민 스타일을 의미','꾸꾸꾸','풀착장','오늘은 각 잡고 꾸꾸꾸 스타일로 가야지!',(SELECT id FROM public.category WHERE category_name = '유행/패션'));
INSERT INTO public.slang ( id, created_time, modified_time, slang_meaning, slang_name, slang_substitutes, slang_example, category_id )  VALUES (gen_random_uuid(),NOW(),NOW(), '아무렇게나 편하게 입은 스타일을 의미','휘뚜루마뚜루','만능','이 바지는 휘뚜루마뚜루라서 매일 입어.',(SELECT id FROM public.category WHERE category_name = '유행/패션'));
INSERT INTO public.slang ( id, created_time, modified_time, slang_meaning, slang_name, slang_substitutes, slang_example, category_id )  VALUES (gen_random_uuid(),NOW(),NOW(), '"Ditto"라는 영어 단어에서 나온 표현으로 동의한다는 의미','디토합니다','동의합니다!','"월요일 너무 싫어!" , "디토합니다..(한숨)"',(SELECT id FROM public.category WHERE category_name = '감정/상태'));
INSERT INTO public.slang ( id, created_time, modified_time, slang_meaning, slang_name, slang_substitutes, slang_example, category_id )  VALUES (gen_random_uuid(),NOW(),NOW(), 'Cmon(컴온)을 씨몬이라 읽으며 생긴 신조어, 감탄사처럼 사용','오우예시몬','오우! ','"너 시험 공부 했어?", "오우예시몬~ 망했지 뭐!"',(SELECT id FROM public.category WHERE category_name = '일상생활'));
INSERT INTO public.slang ( id, created_time, modified_time, slang_meaning, slang_name, slang_substitutes, slang_example, category_id )  VALUES (gen_random_uuid(),NOW(),NOW(), '중요한건 꺾였는데도 그냥하는 마음의 줄임말로 스스로를 응원할 때 사용','중꺾그마','','중꺾그마로 다음 시험 공부를 열심히 해야지!',(SELECT id FROM public.category WHERE category_name = '일상생활'));
INSERT INTO public.slang ( id, created_time, modified_time, slang_meaning, slang_name, slang_substitutes, slang_example, category_id )  VALUES (gen_random_uuid(),NOW(),NOW(), '기절을 영어로 적은 것으로 재미, 기쁨, 감탄 등 긍정적인 감정을 표현할 때 사용','KIJUL','','우리 강아지 너무 귀여워서 나 완전 KIJUL!',(SELECT id FROM public.category WHERE category_name = '감정/상태'));
INSERT INTO public.slang ( id, created_time, modified_time, slang_meaning, slang_name, slang_substitutes, slang_example, category_id )  VALUES (gen_random_uuid(),NOW(),NOW(), ' "맛있다"라는 뜻의 신조어로, 경상도 사투리를 흉내 낸 표현','맛꿀마','맛있다.','마라엽떡 완전 맛꿀마!',(SELECT id FROM public.category WHERE category_name = '일상생활'));
INSERT INTO public.slang ( id, created_time, modified_time, slang_meaning, slang_name, slang_substitutes, slang_example, category_id )  VALUES (gen_random_uuid(),NOW(),NOW(), '누군가를 귀엽거나 애교 있게 부를 때 사용되는 신조어로 언니라는 호칭을 변형한 표현','웅니','언니','우리 웅니 너무 좋아~!',(SELECT id FROM public.category WHERE category_name = '연애/관계'));
INSERT INTO public.slang ( id, created_time, modified_time, slang_meaning, slang_name, slang_substitutes, slang_example, category_id )  VALUES (gen_random_uuid(),NOW(),NOW(), '설명 참고의 줄임말로 "Read desc"라는 영어로도 통하는 표현','설참','설명 참고','이 영상에는 설참이 있으니, 꼭 하단의 설명란을 참고해 주세요.',(SELECT id FROM public.category WHERE category_name = '디지털/인터넷'));
INSERT INTO public.slang ( id, created_time, modified_time, slang_meaning, slang_name, slang_substitutes, slang_example, category_id )  VALUES (gen_random_uuid(),NOW(),NOW(), '강아지를 귀엽게 발음한 말','가나디','강아지','우리 가나디 너무 귀여워ㅠㅠ',(SELECT id FROM public.category WHERE category_name = '일상생활'));
INSERT INTO public.slang ( id, created_time, modified_time, slang_meaning, slang_name, slang_substitutes, slang_example, category_id )  VALUES (gen_random_uuid(),NOW(),NOW(), '슬리퍼와 세권의 합성어로 슬리퍼와 같은 편한 복장으로 각종 여가•편의시설을 이용할 수 있는 주거 권역을 이르는 신조어','슬세권','','우리집은 슬세권이라 너무 편해.',(SELECT id FROM public.category WHERE category_name = '일상생활'));
INSERT INTO public.slang ( id, created_time, modified_time, slang_meaning, slang_name, slang_substitutes, slang_example, category_id )  VALUES (gen_random_uuid(),NOW(),NOW(), '나와 생각이나 행동이 비슷한 사람을 표현하는 신조어','뉴런공유','닮다.','너랑 나랑은 뉴런공유하는 것 같아. 어쩜 이렇게 생각이 비슷할까?',(SELECT id FROM public.category WHERE category_name = ''));
INSERT INTO public.slang ( id, created_time, modified_time, slang_meaning, slang_name, slang_substitutes, slang_example, category_id )  VALUES (gen_random_uuid(),NOW(),NOW(), '일이 내 삶에 스며들었다 의 줄임말로 처음에는 재미없거나 의욕 없던 일에 어느새 빠져들어 동화되는 것을 의미','일며들다','열일하다.','회사가 처음엔 그저 그랬는데 이젠 일에 완전히 일며들었어.',(SELECT id FROM public.category WHERE category_name = '직장/학교'));
INSERT INTO public.slang ( id, created_time, modified_time, slang_meaning, slang_name, slang_substitutes, slang_example, category_id )  VALUES (gen_random_uuid(),NOW(),NOW(), ' "내일 또 출근"의 줄임말','내또출','','아, 내또출이라니 평일이 너무 길다!',(SELECT id FROM public.category WHERE category_name = '직장/학교'));
INSERT INTO public.slang ( id, created_time, modified_time, slang_meaning, slang_name, slang_substitutes, slang_example, category_id )  VALUES (gen_random_uuid(),NOW(),NOW(), '부지런하고 생산적인 삶을 사는 것을 의미','갓생','열심히 살다.','아 오늘 아침에 운동하고 왔어. 완전 갓생사는 기분이야.',(SELECT id FROM public.category WHERE category_name = '일상생활'));
INSERT INTO public.slang ( id, created_time, modified_time, slang_meaning, slang_name, slang_substitutes, slang_example, category_id )  VALUES (gen_random_uuid(),NOW(),NOW(), ' "캘린더 박제"의 줄임말로 일정을 캘린더에 저장해 놓는다는 뜻으로 약속을 잊지 않기 위해 사용하는 단어','캘박','달력에 표기하다.','우리 약속 캘박할게?',(SELECT id FROM public.category WHERE category_name = '일상생활'));
INSERT INTO public.slang ( id, created_time, modified_time, slang_meaning, slang_name, slang_substitutes, slang_example, category_id )  VALUES (gen_random_uuid(),NOW(),NOW(), '"중요한 건 꺾이지 않는 마음"의 줄임말로 2022년 리그 오브 레전드 월드 챔피언십에서 프로게임단 DRX 소속 프로게이머인 데프트 김혁규 선수가 한 인터뷰에서 "저희끼리만 포기하지 않으면, 뭐라도 할 수 있다고 생각했어요."라고 말한 것에서 유래','중꺽마','포기하지 않는 마음','중꺽마야. 시험이 끝날때까지 포기하지마!',(SELECT id FROM public.category WHERE category_name = '감정/상태'));
INSERT INTO public.slang ( id, created_time, modified_time, slang_meaning, slang_name, slang_substitutes, slang_example, category_id )  VALUES (gen_random_uuid(),NOW(),NOW(), ' "느낌이 좋다"의 줄임말로 주로 어떤 사람이 잘생기거나 예쁘거나 멋진 경우, 혹은 상황이나 분위기가 좋을 때 쓰임. 긍정적인 느낌을 표현할 때 사용','느좋','느낌이 좋다.','와, 오늘 날씨 진짜 느좋!',(SELECT id FROM public.category WHERE category_name = '감정/상태'));
INSERT INTO public.slang ( id, created_time, modified_time, slang_meaning, slang_name, slang_substitutes, slang_example, category_id )  VALUES (gen_random_uuid(),NOW(),NOW(), '"갓(God)"과 "테크(Technology)"를 결합한 표현으로, 최고 수준의 기술을 활용하여 경제적 이득을 얻는 방법을 의미.','갓테크','','요즘 갓테크 투자로 수익을 얻고 있어. AI나 블록체인 관련 기술들이 요즘 핫해.',(SELECT id FROM public.category WHERE category_name = '소비/경제'));
INSERT INTO public.slang ( id, created_time, modified_time, slang_meaning, slang_name, slang_substitutes, slang_example, category_id )  VALUES (gen_random_uuid(),NOW(),NOW(), '소소하지만 확실한 행복의 줄임말로, 소비를 통해 작은 행복을 찾으려는 경향','소확행 ','','이 커피 타임이야 말로 내 일상의 소확행이야.',(SELECT id FROM public.category WHERE category_name = '소비/경제'));
INSERT INTO public.slang ( id, created_time, modified_time, slang_meaning, slang_name, slang_substitutes, slang_example, category_id )  VALUES (gen_random_uuid(),NOW(),NOW(), '영혼까지 끌어모아 투자한다는 뜻으로 부동산 가격이 상승하던 시기에 자주 쓰이던 말','영끌','최대한 대출받다.','이번에 집 매매하려고 영끌해서 대출 받았어.',(SELECT id FROM public.category WHERE category_name = '소비/경제'));
INSERT INTO public.slang ( id, created_time, modified_time, slang_meaning, slang_name, slang_substitutes, slang_example, category_id )  VALUES (gen_random_uuid(),NOW(),NOW(), '빚내서 투자한다는 뜻으로 영끌과 비슷한 의미','빛투 ','빛내서 투자한다.','친구가 빛투로 주식을 샀는데, 주가가 떨어져서 걱정이 많아.',(SELECT id FROM public.category WHERE category_name = '소비/경제'));
INSERT INTO public.slang ( id, created_time, modified_time, slang_meaning, slang_name, slang_substitutes, slang_example, category_id )  VALUES (gen_random_uuid(),NOW(),NOW(), '지출을 하지 않는 날을 정해 돈을 절약하는 챌린지','무지출 챌린지','','오늘은 무지출 챌린지 할거야. 0원 쓰는게 목표야.',(SELECT id FROM public.category WHERE category_name = '소비/경제'));
INSERT INTO public.slang ( id, created_time, modified_time, slang_meaning, slang_name, slang_substitutes, slang_example, category_id )  VALUES (gen_random_uuid(),NOW(),NOW(), '음식과 얼리 어답터의 합성어로, 새로운 음식을 빠르게 먹어보고 평가하는 것을 즐기는 사람을 의미','먹리어답터','','내 친구는 먹리어답터라 음식에 관련한 정보가 많아서 좋아!',(SELECT id FROM public.category WHERE category_name = '음식/취미'));